services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.10.2@sha256:58b54bca4c729fcc7f272cfac5086623866430956838de3f5d763fcaf9e64115 #
    container_name: mealie
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - ./config/mealie-data:/app/data/
    networks:
      - reverse-proxy-network
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      BASE_URL: https://recipes.oscarcorner.com.com
    labels:
      traefik.enable: true
      # increase readingTimeouts for the entrypoint used here
      traefik.http.routers.recipes.entrypoints: websecure
      traefik.http.routers.recipes.rule: Host(`recipes.oscarcorner.com`)
      traefik.http.services.recipes.loadbalancer.server.port: 9000
      traefik.http.routers.recipes.tls.certresolver: route53

networks:
  reverse-proxy-network:
    external: true
volumes:
  mealie-data:
