services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:1.45.0
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - reverse-proxy-network
    labels:
      traefik.enable: true
      # increase readingTimeouts for the entrypoint used here
      traefik.http.routers.bookmarks.entrypoints: websecure
      traefik.http.routers.bookmarks.rule: Host(`bookmarks.oscarcorner.com`)
      traefik.http.services.bookmarks.loadbalancer.server.port: 9090
      traefik.http.routers.bookmarks.tls.certresolver: route53

networks:
  reverse-proxy-network:
    external: true
