services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:1.45.0@sha256:61b2eb9eed8e5772a473fb7f1f8923e046cb8cbbeb50e88150afd5ff287d4060
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - reverse-proxy-network
    labels:
      traefik.enable: true
      # increase readingTimeouts for the entrypoint used here
      traefik.http.routers.bookmarks.entrypoints: websecure
      traefik.http.routers.bookmarks.rule: Host(`bookmarks.oscarcorner.com`)
      traefik.http.services.bookmarks.loadbalancer.server.port: 9090
      traefik.http.routers.bookmarks.tls.certresolver: route53

networks:
  reverse-proxy-network:
    external: true
